pulse2percept/pulse2percept

python/effectivecurrent2brightness.py
python/electrode2currentmap.py
python/test_effectivecurrent2brightness.py
python/utils.py

And also a few fixes to things that were breaking the tests. In particular, allocating `cs=ecs` in `electrode_ecs` causes a subtle bug where the two outputs end up being identical. This is a python thing where when two variable names point to the same variable, they both have the same value. So need to preallocate zeros separately to each one!

Function that convert movies to arrays (using opencv, on python2).

---

pulse2percept/effectivecurrent2brightness.py
pulse2percept/electrode2currentmap.py
pulse2percept/files.py
pulse2percept/tests/test_electrode2currentmap.py
pulse2percept/tests/test_files.py
pulse2percept/tests/test_utils.py
pulse2percept/utils.py

A few improvements for the ElectrodeArray class and some helper functions. Most of these are already being used in my experiment branches in one form or the other, but are now also tested and integrated. So the purpose of their existence is mostly to make my life easier. 😸 
Argus I arrays now support legacy naming (L1, L2, ..., L8, M1, M2, ..., M8).
The electrode-to-retina distance depends on electrode type and electrode location. This computation has been moved to `Electrode.set_height` so that heights can be overridden.
Keeping track of electrode names in `ElectrodeArray.names` is redundant, because every `Electrode` has a `name` itself. Setting custom (or new) names would have to be done in both places, otherwise indexing might break. Therefore, I removed `ElectrodeArray.names`. In …

REVIEW mb/fixElectrodeArray

---

pulse2percept/utils/parallel.py

Call `dask.delayed` once up front instead of inside the loop.

RF: Call delayed just once.

---

Makefile

Avoid 'pip cannot uninstall distutils project' (issue #116).
@arokem: Like this? Do `make clean` and `make distclean` still make sense?

pip install

---

Makefile
doc/conf.py
doc/developers/tests.rst
doc/first_steps.rst
doc/getting_started.rst
doc/index.rst
doc/users/index.rst
doc/users/stimuli.rst
pulse2percept/implants/base.py
pulse2percept/implants/tests/test_argus.py
pulse2percept/implants/tests/test_base.py
pulse2percept/io/video.py
pulse2percept/models/axon_map.py
pulse2percept/models/base.py
pulse2percept/models/scoreboard.py
pulse2percept/models/tests/test_axon_map.py
pulse2percept/models/tests/test_base.py
pulse2percept/models/tests/test_scoreboard.py
pulse2percept/stimuli/__init__.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/utils/base.py
pulse2percept/utils/tests/test_convolution.py
setup.py

In the future, this might replace `TimeSeries`.

Add Stimulus object

---

pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py

[REF] Refactor Stimulus object

---

doc/index.rst
doc/users/faq.rst
doc/users/news.rst
doc/users/references.rst
pulse2percept/implants/base.py

PR #140 factored out the bibliography from `doc/users/news.rst`, but accidentally forgot to git add the new file, `doc/users/references.rst`. This PR brings it back and adds some missing references.

[DOC] Restore bibliography

---

pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/base.py
pulse2percept/implants/bva.py
pulse2percept/implants/tests/test_base.py
pulse2percept/models/base.py
pulse2percept/models/tests/test_base.py
pulse2percept/stimuli/base.py
pulse2percept/utils/base.py

Refactors `PrettyPrint.get_params` into `_pprint_params` to clarify its purpose and hide it in the docs.

[REF] Pretty print class attributes

---

doc/developers/style_guide.rst
doc/index.rst
pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/base.py
pulse2percept/implants/bva.py
pulse2percept/implants/tests/test_alpha.py
pulse2percept/implants/tests/test_argus.py
pulse2percept/implants/tests/test_base.py
pulse2percept/implants/tests/test_bva.py
pulse2percept/models/axon_map.py
pulse2percept/models/base.py
pulse2percept/models/scoreboard.py
pulse2percept/models/tests/test_axon_map.py
pulse2percept/models/tests/test_base.py
pulse2percept/models/tests/test_scoreboard.py
pulse2percept/models/tests/test_watson2014.py
pulse2percept/models/watson2014.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/stimuli/tests/test_pulse_trains.py
pulse2percept/utils/__init__.py
pulse2percept/utils/base.py
pulse2percept/utils/tests/test_base.py

Adds [`__slots__`](https://docs.python.org/3/reference/datamodel.html#slots) to all relevant classes (see issue #123). This has the following advantages:
- Slots can reduce memory usage by preventing the creation of `__dict__` and `__weakref__`. This is especially useful when a large number of objects is created (e.g., `TimeSeries` for each electrode, copied to each core)
- Slots can speed up attribute lookup
- Slots prevent the user from adding more class attributes (e.g., `model.newvar = 3`), which is exactly what `utils.FrozenClass` was trying to achieve

[REF] Add __slots__

---

pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py

`Stimulus` indexing was wrong for the following cases:
- string indices for electrodes; e.g., `stim['A1']`, `stim['A1', 0.4]`, `stim[['A1', 'B2'], :]`
- binary indexing; e.g., `stim[stim.electrodes != 'B1', :]`, `stim[:, stim.time < 0.4]`
In addition, you can now slice+interpolate the time axis; e.g., `stim[:, 0.3:2.5:0.01]`

[FIX] Stimulus indexing

---

pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/bva.py
pulse2percept/implants/tests/test_bva.py
pulse2percept/version.py

Fixes a race condition in the BVA24 constructor that makes `p2p.implants.BVA24(stim={'1': 1})` fail, whereas `bva = p2p.implants.BVA24(); bva.stim = {'1': 1}` works (see issue #185).

[FIX] Race condition in stimulus assignment for BVA24

---

pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/base.py
pulse2percept/implants/tests/test_alpha.py
pulse2percept/implants/tests/test_base.py

Fixes `ElectrodeGrid` naming convention when there are more than 26 alphabetic rows/columns (issue #189): new ordering is `A-Z`, then `AA-AZ`, then `BA-BZ`, etc.

[FIX] ElectrodeGrid naming convention

---

examples/models/plot_horsager2009.py
pulse2percept/datasets/horsager2009.py
pulse2percept/datasets/tests/test_horsager2009.py

Allows for a subset of the Horsager be selected (see issue #213):
```
from pulse2percept.datasets import load_horsager2009
data = load_horsager2009(subjects=['S05', 'S06'], electrodes='A1')
```

[ENH] Subset selector for Horsager data

---

pulse2percept/stimuli/base.py
pulse2percept/stimuli/setup.py
pulse2percept/stimuli/tests/test_base.py

Skips the (unnecessary) merging of time axes when a `Stimulus` is created from a large NumPy array (issue #218), thereby speeding up the loading of videos.

[ENH] Merging of Stimulus time axes

---

pulse2percept/models/base.py

This adds an option to `model.find_threshold` that lets the user specify the list of time points (`t_percept`) to be used with `model.predict_percept`.

[ENH] Specify t_percept for find_threshold

---

examples/implants/plot_custom_electrode_array.py

Remove `AxonMapModel` from the custom array gallery example (issue #227).

[DOC] Remove AxonMapModel from plot_custom_electrode_array.py

---

examples/models/plot_horsager2009.py
pulse2percept/models/_nanduri2012.pyx
pulse2percept/models/base.py
pulse2percept/models/nanduri2012.py
pulse2percept/models/tests/test_nanduri2012.py

`Nanduri2012Model` produces much smaller output than `Horsager2009Model`. This adds an optional scaling factor to the model output.

[ENH] Add option to scale Nanduri output

---

pulse2percept/stimuli/images.py
pulse2percept/stimuli/tests/test_images.py

Adds an option where one of the `resize` dimensions of an `ImageStimulus` can be -1, just like `numpy.reshape`.

[ENH] Resize ImageStimulus

---

pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py

Replace `percept.get_brightest_frame()` with `percept.max()`: can return either brightest pixel or brightest frame.

[ENH] add percept.max()

---

README.rst
doc/index.rst
doc/install.rst
doc/users/release_notes.rst
examples/stimuli/plot_image_stim.py
pulse2percept/models/_beyeler2019.pyx
pulse2percept/models/_horsager2009.pyx
pulse2percept/models/_nanduri2012.pyx
setup.py

This PR adds optional OpenMP support for all platforms: if available, runs code in parallel, else behavior is unchanged (see issue #138).

[ENH] Add OpenMP support

---

.github/workflows/build.yml
azure-pipelines.yml
requirements.txt

Setuptools 50.0 broke numpy/distutils.
One option is to set the `SETUPTOOLS_USE_DISTUTILS` environment variable to "stdlib". We'd have to do that in all the Windows builds, e.g. `azure-pipelines.yml`:
```
- powershell: |
$env:SETUPTOOLS_USE_DISTUTILS = "stdlib"
```
This would fix our tests run with GitHub Actions and the pip-installable stable version. However, this would not help people who `pip install git+https://github.com/pulse2percept/pulse2percept`.
Instead, we prefer to require `setuptools<50.0` for now.

[FIX] setuptools 50.0 on Windows2019

---

pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/tests/test_pulse_trains.py

This PR fixes the issue where stimuli get cut off/trimmed to the wrong length in the case that `stim_dur < 1000/freq`. The new and corrected behavior is that a pulse train will cut the requested length, even if that means that an individual pulse is cut in half.
Example: `p2p.stimuli.BiphasicPulseTrain(1, 10, 0.45, stim_dur=2).plot()`
(Cutting pulses in half should only happen when working with odd numbers; e.g., for `p2p.stimuli.BiphasicPulseTrain(123.45, 10, 0.45, stim_dur=40.77)`)

[FIX] PulseTrain length when stim_dur < 1000/freq

---

pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py

`stim.plot(time=(t_min, t_max))` should include `t_min` and `t_max` even when they need to be interpolated (issue #202)

[FIX] stim.plot() should include end points

---

examples/models/plot_nanduri2012.py
pulse2percept/implants/base.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/stimuli/tests/test_pulse_trains.py
pulse2percept/stimuli/videos.py

Simplifies and speeds up stimulus interpolation by switching from `scipy.optimize.interp1d` to the linear 1D `np.interp`.

[FIX] Switch to np.interp for stimulus interpolation

---

pulse2percept/stimuli/__init__.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/pulses.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/stimuli/tests/test_pulse_trains.py
pulse2percept/stimuli/tests/test_pulses.py
pulse2percept/utils/__init__.py
pulse2percept/utils/base.py
pulse2percept/utils/tests/test_base.py

[FIX] Stimulus dt for merging time axes

---

examples/models/plot_horsager2009.py
examples/stimuli/plot_pulses.py
examples/stimuli/plot_sinusoidal.py
pulse2percept/models/tests/test_horsager2009.py
pulse2percept/stimuli/__init__.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/pulses.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/stimuli/tests/test_pulse_trains.py
pulse2percept/stimuli/tests/test_pulses.py

Overload arithmetic operators of the `Stimulus` object:
- add/subtract/multiply/divide amplitudes element-wise
- negate
- append other stimulus
- shift stimuli in time
This PR closes #300.

[ENH] Add Stimulus arithmetic

---

pulse2percept/models/beyeler2019.py
pulse2percept/models/tests/test_beyeler2019.py

The default parameters of the `AxonMapModel` are too optimistic. Update them to more reasonable values.

[ENH] Update the default values for `rho` and `axlambda`

---

pulse2percept/models/tests/test_horsager2009.py
pulse2percept/stimuli/__init__.py
pulse2percept/stimuli/tests/test_pulses.py

The smallest stimulus time step got accidentally reverted to an earlier version. This PR corrects that mistake and fixes the tests.

[FIX] Set stimulus DT=1e-3ms

---

pulse2percept/models/base.py
pulse2percept/models/tests/test_base.py

This PR adds a `set_params` method to `BaseModel` so it can be used in sklearn contexts (e.g.,  `GridSearchCV`).

[ENH] Add model.set_params() for sklearn compatibility

---

examples/datasets/plot_data_beyeler2019.py
pulse2percept/datasets/beyeler2019.py
pulse2percept/datasets/tests/test_beyeler2019.py

Due to a recent HDF5 change, strings in the Beyeler2019 dataset are stored as bytestrings, which breaks the subset selection (e.g., `fetch_beyeler2019(subjects='S2')`. This PR fixes that.

[FIX] HDF5 decoding of bytestrings

---

pulse2percept/models/beyeler2019.py
pulse2percept/models/tests/test_beyeler2019.py

When building the axon map model, a KDTree is now used to find the nearest axon to each simulated point, instead of searching over each axon segment. This changes closest axon lookup time to scale logarithmically in number of axon segments instead of linearly, resulting in speedups of around 150-200x (for closest axon lookup, not for build) using default parameters. The remaining bottleneck in building the model is calculating axon contribution.
Using KDTree is now the default. This can be overridden by passing use_legacy_build=True in the constructor, which uses the old method of searching over all axons. 
The default number of axons is now set to 1000. This could easily be set much higher without significant effect on build time. 
Full list of changes:
- Added [cKDTree …

[ENH] Add KDTree to find closest axon in AxonMapModel

---

pulse2percept/stimuli/images.py
pulse2percept/stimuli/tests/test_images.py
pulse2percept/stimuli/tests/test_videos.py
pulse2percept/stimuli/videos.py
pulse2percept/utils/__init__.py
pulse2percept/utils/images.py
pulse2percept/utils/tests/test_images.py

[ENH] Add image processing methods for VideoStimulus

---

pulse2percept/models/beyeler2019.py
pulse2percept/models/tests/test_beyeler2019.py

Previously axon streaks were way too long. This was because the distance along the axon was not being calculated correctly. Previously, the code in calculate_axon_contributions took the cumulative sum of the distance squared between each segment. Now, it sums the distances, and squares at the end. 
Test cases for calculate_axon_contribution and predict_percept were also updated

[FIX] Axon streak length 

---

.github/workflows/build.yml
README.rst
azure-pipelines.yml
doc/install.rst
setup.py

RIP Python 3.5 - it has reached its [end of life](https://endoflife.date/python). p2p v0.7+ will only support Python 3.6+.

[FIX] Deprecate Python 3.5, add 3.9 to test suite

---

doc/topics/stimuli.rst
pulse2percept/models/base.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/images.py
pulse2percept/stimuli/pulse_trains.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/stimuli/tests/test_pulse_trains.py
pulse2percept/stimuli/videos.py

Previously, stimulus metadata was lost in various places as stimuli were created, and during percept prediction.
Now, metadata information is passed along as stimuli are created/manipulated.
If a stimulus is created from a collection of sources, the stimulus object collects the metadata from each of the sources and stores it in the corresponding electrode in stim.metadata['electrodes']
Additionally, BiphasicPulseTrain is modified to store its stimulus parameters (such as frequency, amplitude, etc) in its metadata. This ensures the information is not lost when a stimulus is created from multiple BiphasicPulseTrains, and enables extension models such as BiphasicAxonMapModel
New test cases were added to test stimulus metadata

[ENH] Stimulus metadata improvements

---

pulse2percept/stimuli/videos.py

This PR fixes a bug that loses the `time` axis when rotating a grayscale video.

[FIX] Time axis when rotating a grayscale video

---

examples/models/plot_axon_map.py

Use longer axon streaks in `plot_axon_map.py` gallery example

[DOC] Use longer axon streaks in gallery example

---

examples/datasets/plot_data_beyeler2019.py
pulse2percept/datasets/beyeler2019.py
pulse2percept/datasets/tests/test_beyeler2019.py
pulse2percept/models/base.py
pulse2percept/viz/__init__.py
pulse2percept/viz/argus.py
pulse2percept/viz/tests/test_argus.py

This PR provides a number of enhancements for the Beyeler2019 dataset (issue #344):

[ENH] Update Beyeler2019 dataset

---

pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py

Fixes a bug where if the user passed vmin and vmax parameters to percept.plot() they were ignored and reset to frame.min() and frame.max().

[FIX] Fix percept.plot() normalization bug

---

pulse2percept/stimuli/tests/test_videos.py
pulse2percept/stimuli/videos.py

When `VideoStimulus` loads a video from file, it uses the wrong frame rate

[FIX] Fix frame rate of VideoStimulus loaded from file

---

doc/users/release_notes.rst
examples/datasets/plot_data_beyeler2019.py
examples/implants/plot_electrode_grid.py
examples/implants/plot_implants.py
examples/models/plot_axon_map.py
pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/bvt.py
pulse2percept/implants/electrode_arrays.py
pulse2percept/implants/prima.py
pulse2percept/implants/tests/test_alpha.py
pulse2percept/implants/tests/test_argus.py
pulse2percept/implants/tests/test_bvt.py
pulse2percept/implants/tests/test_electrode_arrays.py
pulse2percept/implants/tests/test_prima.py
pulse2percept/stimuli/tests/test_videos.py

To be consistent with all the other submodules, implants should use degrees for rotations, not radians (closes #326).

[REF] Make implants use degrees for rotations

---

pulse2percept/percepts/base.py
pulse2percept/stimuli/videos.py

`Percept.play()` and `VideoStimulus.play()` were missing the first frame due to wrong initialization (closes #322)

[FIX] Missing first frame in percept.play()

---

pulse2percept/implants/base.py
pulse2percept/implants/tests/test_base.py

When a stimulus has the wrong number of electrodes for `implant.stim`, the error message is confusing (closes #355)

[FIX] Error message for number of electrodes in implant.stim

---

pulse2percept/version.py
pulse2percept/viz/argus.py
pulse2percept/viz/tests/test_argus.py

Fix the visualization of the axon map in `p2p.viz.plot_argus_phosphenes` and its simulated phosphene equivalent (closes issue #365)

[FIX] Axon map in Argus plotters

---

doc/users/release_notes.rst
pulse2percept/models/beyeler2019.py

Replace `np.insert` with `np.concatenate`, get an immediate speed boost.
To get even a bigger speed boost, we could translate `calc_axon_contribution` to Cython - however, the function does a lot of re-indexing, flipping indices, and extending arrays. This sounds like a pain to do in Cython...

[ENH] Speed up AxonMap build

---

pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py
pulse2percept/stimuli/videos.py

Various improvements for `Percept`:

[FIX] Percept plotting and animation

---

doc/users/release_notes.rst
pulse2percept/implants/bvt.py
pulse2percept/implants/tests/test_bvt.py

Changes electrode naming convention from '1' through '21' to 'C1' through 'C21'. The indexer gets confused with the numbers: `implant[1]` is not the same as `implant['1']`

[FIX] BVT24 electrode naming convention

---

doc/topics/implants.rst
examples/implants/plot_electrode_grid.py
pulse2percept/datasets/tests/test_beyeler2019.py
pulse2percept/implants/alpha.py
pulse2percept/implants/argus.py
pulse2percept/implants/base.py
pulse2percept/implants/bvt.py
pulse2percept/implants/electrode_arrays.py
pulse2percept/implants/electrodes.py
pulse2percept/implants/prima.py
pulse2percept/implants/tests/test_alpha.py
pulse2percept/implants/tests/test_argus.py
pulse2percept/implants/tests/test_base.py
pulse2percept/implants/tests/test_electrode_arrays.py
pulse2percept/implants/tests/test_electrodes.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/nanduri2012.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py
pulse2percept/viz/argus.py
pulse2percept/viz/axon_map.py

This PR fixes miscellaneous usability issues & adds several upgrades for interacting with implants:

[ENH] Various implant upgrades

---

pulse2percept/stimuli/psychophysics.py

The docstring for `BarStimulus` and `GratingStimulus` did not specify the units for `height` and `width` (it's pixels)

[FIX] BarStimulus, GratingStimulus docstring

---

pulse2percept/models/temporal.py

The default value in `FadingTemporal` for `tau` was set to 0.01 - that's way too small. Change to 100

[FIX] More sensible default value for tau in FadingTemporal

---

pulse2percept/models/granley2021.py
pulse2percept/models/tests/test_granley2021.py

Previously `BiphasicAxonMapSpatial` failed to return the correct effect model parameter unless it was a part of `self.bright_model`
Failing test case to test that every default effect model parameter is accessible (now added):
```
for atr in ['a' + str(i) for i in range(0, 10)]:
npt.assert_equal(hasattr(model, atr), True)
```

[FIX] Fix missing BiphasicAxonMapModel effect model params

---

pulse2percept/utils/geometry.py

Use [convex hull](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html) to show the range of x/y values simulated with `model.plot`

[ENH] Use convex hull for model.plot

---

pulse2percept/implants/electrode_arrays.py
pulse2percept/implants/tests/test_electrode_arrays.py
pulse2percept/implants/tests/test_prima.py

[ENH] ElectrodeGrid spacing and hex grid layout

---

pulse2percept/models/base.py

Previously, if called 2 frames below the constructor, `BaseModel` `__getattr__` raises an [attribute error](https://github.com/pulse2percept/pulse2percept/blob/master/pulse2percept/models/base.py#L694-L699), which is caught later and the attribute created. 
The problem is that it is also possible to be 2 frames below a different classes `__init__` , and then during `__getattr__` even if the spatial/temporal part of the model has the attribute, this init check is done first, so an exception is still raised. 
It is actually possible to completely remove this `__init__` check. This is because the only possibilities are that 1) we already have the attribute in either the spatial or the temporal model, in which case just return it. Or 2) the attribute does not exist in either the spatial or …

[FIX] Fix bug on accessing model parameters inside __init__ of another class

---

doc/users/faq.rst
examples/models/plot_retinotopy.py
pulse2percept/models/base.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/granley2021.py
pulse2percept/models/nanduri2012.py
pulse2percept/models/tests/test_base.py
pulse2percept/models/tests/test_beyeler2019.py
pulse2percept/models/tests/test_granley2021.py
pulse2percept/models/tests/test_nanduri2012.py
pulse2percept/utils/__init__.py
pulse2percept/utils/geometry.py
pulse2percept/utils/tests/test_geometry.py
pulse2percept/viz/argus.py

This PR refactors retinotopy used to convert between retinal and visual field coordinates:
Related bug fixes:
-  [x] `AxonMapModel` did not always use `dva2ret` correctly: When calculating the bundle locations, `dva2ret` was applied to the `x` and `y` coordinates separately instead of `r` (polar). Fortunately, the effect on the output is minimal, since within 40deg dva it's pretty much a 1-1 mapping (see Fig. A1 in Watson, 2014).

[REF] [FIX] Refactor retinotopy

---

examples/models/plot_retinotopy.py
pulse2percept/models/_beyeler2019.pyx
pulse2percept/models/_granley2021.pyx
pulse2percept/models/_nanduri2012.pyx
pulse2percept/models/base.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/tests/test_base.py
pulse2percept/utils/geometry.py
pulse2percept/utils/tests/test_geometry.py

Improves handling/usability of `pulse2percept.utils.Grid2D`:
Example `grid.plot()` for the `Watson2014DisplaceMap`:

[ENH] Grid2D NaN & plot upgrades

---

pulse2percept/models/granley2021.py
pulse2percept/models/tests/test_granley2021.py

This PR contains 2 Biphasic model updates:
1) Closes #423; now you can set effects model parameters (e.g. a0-a10) in the `BiphasicAxonMapModel` constructor. 
2) Percept brightness scale now matches Beyeler 2019 instead of Nanduri 2012 / Greenwald 2009.
**1)** Previously, if a parameter was passed, it couldn't be distributed to the effects models because the effects models had not been instantiated yet during model initialization. 
Instantiating the effect models before calling `super.__init__()`, as suggest in bug report, doesn't work due to `getattr` / `setattr`logic , and because pre-initialization the `Frozen` class hasn't been applied yet so it cannot access the correct superclass `getattr`. The simplest way remaining seems to be simply setting all of the attributes passed in …

[FIX][REF] Biphasic parameter update and initialization fix 

---

pulse2percept/models/base.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/granley2021.py
pulse2percept/models/nanduri2012.py
pulse2percept/models/tests/test_granley2021.py
pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py

Adds an option to limit the number of gray levels in a percept.

[ENH] Add percept gray levels

---

pulse2percept/implants/base.py
pulse2percept/implants/tests/test_base.py
pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py
requirements.txt

A deactivated electrode should not be able to receive a stimulus. This works if the electrode is deactivated first, before a stimulus is assigned. But this doesn't work if the electrode is deactivated after a stimulus was assigned. This PR fixes that by providing a `Stimulus.remove(electrode)` method.

[FIX] Ignore stimuli of deactivated electrodes

---

pulse2percept/utils/geometry.py
pulse2percept/utils/tests/test_geometry.py

This PR fixes issue #442, when `step` of a `Grid2D` object is a tuple:
```
p2p.utils.Grid2D((-5, 5), (-5, 5), step=(0.5, 1)).plot(style='cell')
```

[FIX] Grid2D plot when step is a tuple

---

pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py
pulse2percept/utils/constants.py
pulse2percept/utils/stats.py
requirements.txt

Through a combination of updates from our software dependencies, two tests are now breaking:

[FIX] mimread and circ_r2_score due to external dependency updates

---

requirements.txt

SciPy 1.7.2 applied some bug fix to the handling of BLAS/LAPACK that accidentally breaks our wheels. The issue is still present in 1.8.0. For now, we limit the allowed SciPy version

[FIX] SciPy breaks wheels

---

pulse2percept/models/base.py

Adds `__hash__` functions to `Model` and `BaseModel`, which allows Jax based models to work again. 
Closes #471 

[FIX] Models are now hashable

---

pulse2percept/stimuli/base.py
pulse2percept/stimuli/tests/test_base.py

This PR addresses the issue where Stimuli would become corrupted when created from multiple Stimuli. The issue was in the merging of time axes, where not enough unique points were collected, leading to corrupted Stimuli when interpolated.
Closes #392 

[BUG] Fix Corrupted Multi-Stimuli

---

examples/stimuli/plot_psychophysics.py
pulse2percept/stimuli/__init__.py

This pull request adds a page the the example gallery that shows an example of creating a psychophyscs-based stimulus, customizing it, and passing it to an implant.
Closes #324 

[DOC] Add Gallery Example for BarStimulus and GratingStimulus

---

pulse2percept/implants/base.py
pulse2percept/implants/electrode_arrays.py
pulse2percept/implants/tests/test_base.py

This introduces an easy way to color the electrode array in `implant.plot()` based on the amplitude of the stimulating electrodes. 
`implant.plot()` now accepts a `color_stim` parameter, defaulting to False. If True, the amplitude of each electrode is mapped to the color of each active electrode in the plot. The color map can also be specified with the `cmap` parameter.
I'm currently not sure what the best default colormap to use is. 
**Example**: 
Default behavior unchanged
```
implant = ArgusII()
implant.stim = {'B4': BiphasicPulseTrain(5, 2, 1), 'C5': BiphasicPulseTrain(5, 3, 1), 'D6': BiphasicPulseTrain(5, 4, 1)} 
implant.plot()
```
A single monotonically increasing cmap (e.g. 'OrRd') could make sense:
```
implant.plot(color_stim=True, cmap='OrRd')
plt.colorbar()
```
Or having …

[ENH] Allow easy stimulus coloring in implant.plot()

---

pulse2percept/implants/electrode_arrays.py

Changes `plt.sci ` to `ax._sci` so the current image is set on the correct axis

[BUG] Fix implant plot coloring with multiple axes

---

pulse2percept/models/base.py

This changes `SpatialModel.predict_percept` to only call `_predict_spatial` for a compressed stimulus where the distribution of amplitudes across electrodes is unique. 
Performance improvement with default `AxonMapModel` on my laptop:
- With 20Hz `BiphasicPulseTrain`: 6.5ms vs 309ms, **~50x Speedup**
- With 250Hz `BiphasicPulseTrain`: 57ms vs 5s, **~90x Speedup**
- With random frequency `BiphasicPulseTrain` on 60 electrodes: 13.5min vs 4min , **~3.5xSpeedup**
Closes #456

[ENH] Only run predict percept on unique time points

---

doc/users/references.rst
examples/implants/plot_argus.py
pulse2percept/datasets/beyeler2019.py
pulse2percept/datasets/tests/test_beyeler2019.py
pulse2percept/percepts/base.py
pulse2percept/stimuli/__init__.py
pulse2percept/stimuli/videos.py
pulse2percept/viz/argus.py
pulse2percept/viz/tests/test_argus.py

Add a gallery example that simulates the vision provided by Argus II, along with some minor enhancements:

[DOC] Add plot_argus.py example

---

pulse2percept/models/base.py
pulse2percept/percepts/tests/test_base.py

Doesn't set `stim.time` if there is only 1 unique time point
Closes #503

[FIX] Predict percept bug with single unique time point

---

pulse2percept/percepts/tests/test_base.py

`percept.save()` tests currently fail locally and on github. I think imagio-ffmpeg changed slightly. Now, attempting to save a multi-frame percept as a image (e.g. '.jpg') raises a `RuntimeError`, not the `ValueError` that was previously expected.
To fix I just changed the tests to expect a `RuntimeError`

[TST] Update percept.save tests

---

requirements-dev.txt

Using `sklearn` with pip is deprecated and is now an error, change to `scikit-learn`

[MNT] Update sklearn in requirements

---

doc/_static/css/custom.css

Sphinx-gallery updated and it treats `_static/custom.css` slightly differently, causing the issue where thumbnails overflow their boxes. 
**E.G.:**
Just removing the custom thumbnail sizing in `custom.css` fixes the issue. The thumbnails are smaller than before, but after ~20 minutes I couldnt figure out how to make them bigger without overlapping, and I think it currently looks fine, so I just left it.
**New Version:**

[DOC] Fix gallery thumbnail images

---

pulse2percept/implants/base.py
pulse2percept/implants/tests/test_base.py

Adds a check in `ProsthesisSystem`'s `stim` setter. This causes empty inputs (e.g. `stim=[]` or `stim={}`) to set `ProsthesisSystem.stim` to `None`. Previously, the setter would try to create a `Stimulus` object which would cause various errors depending on the type (dict, list, etc.). With this change, passing an empty stimulus will now have the same effect as passing `stim=None`, which is that calling `model.predict_percept` on an implant with this stimulus will simply output `None` without throwing an error.
Closes #498

[FIX] Add check for empty stimulus

---

pulse2percept/implants/electrode_arrays.py

Right now electrode numbers appear under the electrode patches, so you cant really ever see them unless the plot is huge enough that the full name fits inside the electrode. If a user is taking the time to specify `annotate=True`, then annotations should always be legible.
**Old**:
**New:**

[FIX] Fix electrode numbering annotation in implant.plot()

---

.github/workflows/build.yml
.github/workflows/wheels.yml
doc/requirements.txt

This PR fixes 2 things:
1. Ubuntu 18.04 is no longer supported and Github actions will no longer run it. Updated version uses only 20.04 and 22.04
2. A new Jax update causes tests to fail. Since jax is such a small part of p2p and will likely be removed soon, I didn't bother trying to figure out how to fix it, and just required the version to be <=0.4.3

[MNT][FIX] Remove outdated ubuntu workflows, add Jax version requirement

---

pulse2percept/datasets/perezfornos2012.py

`pandas.DataFrame.append` no longer exists in version 2.0, which causes our tests to fail. I changed it to use the recommended `pd.concat` instead.
https://pandas.pydata.org/pandas-docs/version/1.5/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append

[FIX] Replace DataFrame.append with pd.concat

---

pulse2percept/implants/__init__.py
pulse2percept/implants/ensemble.py
pulse2percept/implants/tests/test_ensemble.py

Adds the `EnsembleImplant` which extends `ProsthesisSystem`. This class is meant for simulating multiple implants meant to be used in tandem, such as CORTIVIS, but can be used with any implant type. It takes a list or dict of `ProsthesisSystem` objects and combines their electrode arrays.
If the input is a list, the new electrodes are named in the form `idx`-`electrode_name` where `idx` is the index of the implant in the list.
If the input is a dict, the new electrodes are named in the form `key`-`electrode_name` where `key` is the key of the implant in the dict.
Closes #527

[ENH] Add Ensemble implant

---

pulse2percept/percepts/base.py
pulse2percept/percepts/tests/test_base.py
pulse2percept/stimuli/images.py
pulse2percept/stimuli/tests/test_images.py

This PR fixes several issues.
1. When loading an `ImageStimulus`, we were passing a `format` keyword. This is not supported in newer versions of skimage & imageio, and has been removed. (Originally replaced by the `extension` keyword but this is not supported by the TIFF image loader for some reason). (Bug referenced in #549) 
2. We were unable to save ImageStimulus (which has dtype `float32`) as PNG, JPEG, etc. For these file-types, we scale to `uint8` before saving and output a warning that the data has been scaled/compressed. TIFF files are saved with full original precision.
3. When saving a video percept, we were passing a `fps` keyword. This is no longer supported by imageio for saving GIFs & other miscellaneous file types. This has been supplemented by a `duration` keyword argument …

[FIX] scikit-image/imageio bugfixes (kwargs, saving float32 to png, unexpected saved percepts)

---

.github/workflows/wheels.yml

Previously, wheels workflows used the macos-10.15 runner. This runner is no longer supported in GitHub Actions as of August 2022 (no clue how this didn't break tests until recently).
This PR changes GitHub workflows to use macos-12 instead of macos-10.15.

[FIX] Update GitHub wheels actions to use available MacOS runner

---

.github/workflows/build.yml
.github/workflows/wheels.yml

Keeps Mac os runner updated (12), but removes build for python 3.7 on mac. 
There is some obscure installation error with libbz2 on mac that is preventing tests from passing for python 3.7 on mac targets. After some initial digging it does not seem like there is an obvious fix, and since python 3.7 is officially deprecated in a couple of days anyways, I am just removing this test.

[FIX] Github wheels for mac

---

pulse2percept/implants/cortex/cortivis.py
pulse2percept/models/cortex/tests/test_base.py

Changes cortivis electrode numbering to match Fernandez 2022 paper.

[REF] Cortivis Electrode Numbering

---

requirements-dev.txt
requirements.txt

Currently pulse2percept fails to import without pandas and joblib, which are only listed in requirements-dev.txt
Closes #563 

[FIX] Move requirements from requirements-dev that are required to run.

---

doc/requirements.txt

With a fresh install of p2p and `doc/requirements.txt`, building docs currently fails:
`sphinx.errors.ExtensionError: Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2'`
Jinja is imported by sphinx, and our sphinx version does not allow for the newest jinja update. 
We could alternatively upgrade to the newest version of sphinx, but that creates a whole other group of issues. This is an easier fix for now atleast.

[DOC] Pin jinja version to <3.1

---

.github/workflows/wheels.yml

cibuildwheel currently fails to build all python versions for ubuntu. After a long and painstaking search for a `cibw_before_build_linux` that worked, I ended up just updating the cibuildwheel to use the current 2.16.2 (instead of long outdated 2.1.3) cibuildwheel release. 
Also updates to use ubuntu22.04
Replaces PR #569

[MNT][FIX] Update cibuildwheel

---

pulse2percept/implants/base.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/cortex/tests/test_base.py
pulse2percept/models/tests/test_beyeler2019.py
pulse2percept/models/tests/test_granley2021.py
pulse2percept/models/tests/test_nanduri2012.py
pulse2percept/topography/base.py
pulse2percept/topography/retina.py
pulse2percept/topography/tests/test_base.py
pulse2percept/topography/tests/test_retina.py

This issue originated from a bug report (#559 ) showing `AxonMapModel` axons not plotting correctly for `use_dva`:
```
model = p2p.models.AxonMapModel(
loc_od=(10.5, 4.5),
xrange=(-15, 5),  # dva
yrange=(-2, 10),  # dva
xystep=0.25,)
model.build()
fig, axs = plt.subplots(1,2)
model.plot(use_dva=False, ax=axs[0])
model.plot(use_dva=True, ax=axs[1])
fig.set_constrained_layout(True)
```
However, the following issues with the plot revealed some deeper implementation details and a AxonMapModel bug
- The plotted simulated grid (y from [-2, 10]) is correct ONLY in dva, and is not correct in the retinal plot.
- The optic disc location (y_od = 4.5) is ONLY correct in dva, and not correct in the retinal plot.
- The axon locations look correct in the retinal plot, but only because the optic disc …

[FIX] Y axis treatment in retinotopy, visual field, and Grid2D. Fix AxonMapModel OD location

---

.readthedocs.yml

readthedocs.yml is out of date. Build currently fails because the build.os option is not set. Also bump to use python 3.10 for docs

[DOC] Update readthedocs.yml

---

pulse2percept/implants/__init__.py
pulse2percept/models/__init__.py

Looks like after updating `setup.py`, including cortex subpackages in the parent's `__init__.py` no longer causes a circular import error.
Cortex packages now import as expected.
Closes #581 

[FIX][MNT] Fix cortex packages not importing as expected

---

.github/workflows/build.yml
doc/conf.py
examples/datasets/plot_data_nanduri2012.py
examples/implants/plot_implants.py
examples/stimuli/plot_image_stim.py
pulse2percept/models/_horsager2009.pyx
pulse2percept/models/_nanduri2012.pyx
pulse2percept/models/nanduri2012.py
pulse2percept/models/tests/test_nanduri2012.py

This PR is meant to make it so docs can build again. But the reason docs were failing were because the Nanduri and Horsager models we're suddenly extremely slow. For more details see (#585 ) but the TLDR is that certain fast math functions are for some magical reason no longer fast on specific platforms (even with exactly the same cython version, pip packages, gcc, openmp, etc as fast platforms).
To fix this I simply removed calls to the fast math functions and copy-pasted the function in each place it is specifically needed. Its a strange fix but it works, and I cant figure out how to get the cython functions to work fast.
There are also a few small changes to docs, such as formatting, fixing old imports, etc

[DOC][FIX] Fix docs, remove calls to slow _fast_math cython functions

---

doc/topics/cortical.rst
examples/models/plot_dynaphos.py
pulse2percept/models/cortex/dynaphos.py
pulse2percept/models/cortex/tests/test_dynaphos.py

Adds a cortical tissue activation threshold to the Dynaphos model, to better match the paper. This is a settable parameter (a_thr) and limits when percepts are generated. This also prevents the currently observed behavior where, if a stimulus goes from high amplitude to 0, the generated phosphenes never fully fade.
Updates Dynaphos documentation to match, and adds an example allowing us to reproduce a figure from the paper (with limitations).

[ENH][FIX][DOC] Add Dynaphos activation threshold

---

pulse2percept/stimuli/images.py
pulse2percept/stimuli/tests/test_images.py

In ImageStimulus crop, we now check if y1 > img_shape[0] or x1 > img_shape[1], since x1,y1 are EXCLUSIVE bounds (specified in the docstring). Updates the error message to properly reflect the bottom-right coordinate (y1-1, x1-1).
We also check if the image has color channels so we can index appropriately for cropping.
Closes #564

[FIX] Fix ImageStimulus crop safety checks + 2-channel indexing

---

examples/models/plot_dynaphos.py

Dynaphos docs incorrectly referenced an `EnsembleImplant` when the example uses an `Orion` implant, so this PR just fixes that sentence.

[DOC] Fix incorrect implant mention in Dynaphos docs

---

doc/topics/cortical.rst

Adds a simple `EnsembleImplant` example to the cortex docs. Shows a 2-implant CORTIVIS ensemble. 
Closes #599 

[DOC] Add EnsembleImplant to cortex docs

---

pulse2percept/implants/ensemble.py
pulse2percept/implants/tests/test_ensemble.py

Adds two methods to initialize an `EnsembleImplant` from a set of coordinates. This should generally match the format of `Neuralink.from_neuropythy()`.
`EnsembleImplant.from_coords()` allows the user to pass an implant type (must subclass `ProsthesisSystem`) & a set of locations on the cortex/retina (in µm), or an xrange/yrange/xystep in µm. We then automatically create a set of implants of the given type at the desired locations.
`EnsembleImplant.from_cortical_map()` takes the same parameters as `from_coords()` in addition to a `vfmap` (must be a `CorticalMap` instance and implement `from_dva()`) and `region` (defaults to v1). Locations/coordinates are passed to this function in dva, and internally converted to µm (in the given region).
Possible expansion: `from_retinal_map()`. Not …

[ENH] Add methods to initialize an EnsembleImplant from a list of coordinates

---

doc/topics/implants.rst
pulse2percept/implants/cortex/neuralink.py

Adds neuralink to the implants documentation basic concepts and overrides from_cortical_map for neuralink to choose whether to use from_neuropythy or not depending on type of vfmap passed

[DOC][ENH] Add Neuralink to doc and override from_cortical_map for Neuralink

---

pulse2percept/topography/neuropythy.py
pulse2percept/topography/tests/test_neuropythy.py

The inverse transform for neuropythy visual field map. Uses interpolation between points with known visual field locations using 5 nearest neighbors.

[ENH] Neuropythy *_to_dva

---

pulse2percept/topography/neuropythy.py

Adds error when using neuropythy classes without it being installed, and updated doc with installation instructions

[ENH] Neuropythy doc and error

---

.github/workflows/build.yml
.github/workflows/build_slow.yml
pulse2percept/percepts/tests/test_base.py
pulse2percept/stimuli/tests/test_videos.py

Updates the GitHub actions workflows so that Python is actually installed and setup properly on MacOS runners.
Excludes 3.8 and 3.9 for latest mac since there is no runner, and adds in macos-13 to test these versions. Also installs ffmpeg for latest mac.

[MNT][FIX] Update GitHub actions for MacOS

---

.github/workflows/build.yml
doc/requirements.txt
pulse2percept/models/base.py
pulse2percept/models/cortex/base.py
pulse2percept/models/cortex/tests/test_base.py

Adds a PyTorch backend/engine for the cortex ScoreboardModel. This backend can be selected by passing the argument `engine='torch'` during model initialization.
This also adds the `TorchBaseModel` abstract class which all torch models will subclass.
Closes #611 

[ENH][REF] Torch Scoreboard

---

.github/workflows/build.yml
pulse2percept/implants/__init__.py
pulse2percept/implants/base.py
pulse2percept/implants/tests/test_base.py

This adds a generic rectangle implant, which has been used previously in multiple papers.
Currently if you want to make a custom implant, you have to make a custom electrode grid, then create a prosthesis system subclass wrapping this earray, which is cumbersome, and lacks some of the basic functions that premade implants have.
This adds a generic `p2p.implants.RectangleImplant` which does all this for the user, so they can have an implant with a custom location, shape, spacing, electrode type, etc with one line.
It defaults to the 15x15 implant used in Granley et al 2022 and Granley et al 2023
This also removes codecov (see #632 )

[ENH] Add generic rectangle implant and remove codecov

---

requirements.txt

This limits numpy to be <= 1.26. Another PR (#635) is ready for numpy 2 support, but tests wont pass until neuropythy/pimms is made [np2 compatible ](https://github.com/noahbenson/pimms/pull/6)

[FIX] Hotfix for numpy 2.0

---

conftest.py
pulse2percept/models/beyeler2019.py
pulse2percept/models/cortex/tests/test_base.py
pulse2percept/models/cortex/tests/test_dynaphos.py
pulse2percept/models/horsager2009.py
pulse2percept/models/temporal.py
pulse2percept/models/tests/test_beyeler2019.py
pulse2percept/models/tests/test_granley2021.py
pulse2percept/models/tests/test_horsager2009.py
pulse2percept/models/tests/test_nanduri2012.py
pulse2percept/models/tests/test_temporal.py
pulse2percept/models/tests/test_thompson2003.py
pulse2percept/utils/__init__.py
pulse2percept/utils/testing.py
pyproject.toml
requirements-dev.txt
requirements.txt

Adds timing benchmarking using pytest-benchmark for all models.
This is disabled by default, but can be enabled by passing `--benchmark-enable` to pytest.
Some options could be removed eventually. Right now every model is benchmarked with all engines (serial, cython, and torch), as well as torch on cpu and gpu, and torch with and without compilation. 
Closes #627 
This also adds a barebones pyproject.toml. Eventually we should migrate more setup, installation, and configuration to here (#571)

[ENH] Add benchmarking

---

.github/workflows/build.yml
.github/workflows/wheels.yml
.readthedocs.yml
doc/conf.py
doc/requirements.txt
pyproject.toml

Adds a few lines to pyproject.toml which fixes a bug where after `import pulse2percept as p2p` submodules were not found. Now it searches pulse2percept and pulse2percept/* for submodules (including the parent).
@mbeyeler This is a minimal fix just changing the toml, if you had other additions to pyproject.toml, setup.py, etc in the fix-data-docs branch feel free to add those in or in a separate PR after

[FIX] Submodule import error

---

pulse2percept/implants/ensemble.py
pulse2percept/implants/tests/test_ensemble.py

Fixes a bug where preset stimuli are ignored for each individual implant during ensemble implant creation. Now, it attempts to merge the stimuli, even if they have different times or electrodes. Also merges metatdata to support e.g. BiphasicAxonMapModel
Could consider putting merge_stimuli in the Stimulus class and perfect it at some point.
Also adds tests.
Closes #650

[FIX] Ensemble Implant with multiple stimuli

---

.github/workflows/build.yml
.github/workflows/wheels.yml

Despite our best intentions to install platform-specific dependencies, typos have prevented us from doing so. This PR removes installs and checks that never trigger because 'windows-latest' or 'macos-latest' are not valid values for `runner.os`

[FIX] GitHub Actions
