- matlab/AhujaModel.m
- matlab/AnotherVersionOfModel.m
- python/effectivecurrent2brightness.py
- python/main.py
Here is a new pull request that is my version of the Alan  temporal model.
> Alan model if w draft

- python/oyster.py
- python/stuff.py
This is work in progress. Not ready to be merged.
> Initial commitment for oyster.py.  Includes function jansonious.py

- python/electrode2currentmap.py
- python/test_electrode2currentmap.py
Work in progress -- please don't merge yet.
> Initial implementation of an Electrode class

- python/effectivecurrent2brightness.py
Thanks @rbiswas4 for spotting this!
> Matlab translation in gamma function

- README.md
- python/effectivecurrent2brightness.py
- python/electrode2currentmap.py
Readme now has an overview of the files.
Electrode2currentmap is reorganized
Effectivecurrent2brightness also reorganized to consistof separate functions but is still broken in some mysterious ways.
> varoious changes to electrode2currentmap and effectivecurrent2brightness, improved Readme

- README.md
- python/effectivecurrent2brightness.py
- python/electrode2currentmap.py
- python/notebooks/electrodes2effectivecurrent.ipynb
First pass of an implementation of a stimulus class, which can be passed to an electrode, and together with an instance of a retina object, can return time-series scaled by the effective current spread. We do need to merge other things, before we can merge this, so please don't merge yet.
> Please don't merge: Electrode/stimulus

- python/electrode2currentmap.py
This is so that the x dimension is the first dimension of the resulting
grids, and everything derived from it. 
This should fix all the confusions we were having...
> Fix the meshgrid indexing.

- python/notebooks/ExpDorn2011_parallel.ipynb
- python/notebooks/parfor.ipynb
- python/test_utils.py
- python/utils.py
This extends #24, to also add a notebook with an application of the parfor function to the Dorn experiment.
> Dorn parfor

- python/notebooks/parfor.ipynb
- python/test_utils.py
- python/utils.py
A first pass at how to do parfor with numpy arrays.
> Add a notebook with a potential "parfor" function.

- python/electrode2currentmap.py
- python/test_electrode2currentmap.py
And added some testing as well.
> Fix 1 based idx

- python/effectivecurrent2brightness.py
- python/electrode2currentmap.py
- python/test_effectivecurrent2brightness.py
> Add a helper function to calculate a brightness movie from all the bits.

- python/effectivecurrent2brightness.py
- python/test_electrode2currentmap.py
> Add a testing of the resampling method.

- python/scripts/SingleElectrodes.py
Just wrote code so we can look at what single electrodes look like. Not yet merged with your code making that more modular, but will do that today. But would like to merge it in the meantime so I can run it on the 12 core
> Singleelectrodes

- python/effectivecurrent2brightness.py
- python/scripts/SingleElectrodes.py
- python/scripts/npy2movieSlow.py
converting npy to movies, an example movie fill
> Working version simulating single electrodes, beginning of code for movies without avconv

- python/test_effectivecurrent2brightness.py
- python/test_electrode2currentmap.py
With these additions, tests pass again.
> Add the "height" arguments in the tests.

- setup.py
See also: https://github.com/uwescience/shablona/pull/54
> Add install_requires for smoother pip installation

- .travis.yml
- pulse2percept/electrode2currentmap.py
- pulse2percept/files.py
- pulse2percept/tests/test_electrode2currentmap.py
- pulse2percept/tests/test_files.py
- pulse2percept/tests/test_utils.py
- pulse2percept/utils.py
Add documentation and testing of the `files` module:
> [MRG] Document files module

- .travis.yml
- doc/conf.py
- pulse2percept/api.py
- pulse2percept/files.py
- pulse2percept/retina.py
- pulse2percept/stimuli.py
- pulse2percept/tests/test_utils.py
- pulse2percept/utils.py
Improved deprecation warning system, adapted from [scikit-image](https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/utils.py) and the [Python Wiki](http://wiki.python.org/moin/PythonDecoratorLibrary).
The new deprecation wrapper allows you to specify:
- which function to use instead (`alt_func`)
- a behavior (`'warn'` or `'raise'`)
- the release when the function will be removed (`removed_version`)
The function's doc string is automatically augmented to include a deprecation warning.
> [MERGE] Improved deprecation warnings

- pulse2percept/api.py
- pulse2percept/files.py
- pulse2percept/retina.py
- pulse2percept/tests/test_api.py
- pulse2percept/tests/test_files.py
- pulse2percept/tests/test_retina.py
- pulse2percept/tests/test_utils.py
- pulse2percept/utils.py
SciPy reviewers requested the following changes to the code:
The following changes will make the code equivalent to what is present in the SciPy paper, for a hypothetical 0.2 release.
> [REVIEW] Changes requested from SciPy reviews

- pulse2percept/api.py
Sometimes you just want to plot something real quick, but ``plot_fundus`` currently requires ``set_optic_fiber_layer`` to be run first - which can take a while, and is not really needed anyway. This PR removes that requirement.
> Don't require ``set_optic_fiber_layer`` to be called before ``plot_fundus``

- .travis.yml
- doc/tools/apigen.py
- pulse2percept/api.py
- pulse2percept/files.py
- pulse2percept/implants.py
- pulse2percept/retina.py
- pulse2percept/tests/test_api.py
- pulse2percept/tests/test_files.py
- pulse2percept/tests/test_stimuli.py
- pulse2percept/utils.py
- pulse2percept/viz.py
I added alpha constant to Grid class definition in order to allow changing alpha for passive current spread. In the future, I want to change alpha electrode by electrode. I am not sure how to do that yet, that will come in a future pull request. 
Thanks
Ezgi
> Allow passing alpha constant to grid class

- .travis.yml
Switch from buggy coveralls to codecov
> ENH: Switch to codecov

- pulse2percept/utils.py
- requirements.txt
Should fix this build error: https://travis-ci.org/uwescience/pulse2percept/builds/543060364#L1361
> Scipy factorial

- CODE_OF_CONDUCT.md
Using the covenant standard template
> [ENH] Create CODE_OF_CONDUCT.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Proposed issue templates for bug reports and feature requests.
> [ENH] Add issue templates

- CONTRIBUTING.md
Proposed guidelines for contributing to pulse2percept (adapted from Nypipe).
> [ENH] Add CONTRIBUTING.md

- doc/installation.rst
- examples/notebooks/0.0-example-usage.ipynb
> Windows installation - first draft

- pulse2percept/viz.py
Make `p2p.viz.plot_fundus` work again with new `ProsthesisSystem` object and `AxonMapModel`.
> Fix fundus plot

- .github/PULL_REQUEST_TEMPLATE.md
> [ENH] Create PULL_REQUEST_TEMPLATE.md

- examples/stimuli/plot_pulses.py
Pull request for the issue #132. I wrote simple examples for mono and biphasic stimuli and changing the amplitudes. Please let me know if there are mistakes/more to be added then I can move forward for the pulse trains.  Thanks!
> [DOC] Added examples for monophasic and biphasic stimuli for the issue #132

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.rst
Update the contribution guidelines:
> [STY] Update contribution guidelines

- README.rst
- doc/_static/css/custom.css
- doc/conf.py
- doc/install.rst
- doc/users/api.rst
- doc/users/news.rst
- pulse2percept/__init__.py
- pulse2percept/implants/__init__.py
- pulse2percept/implants/alpha.py
- pulse2percept/implants/argus.py
- pulse2percept/implants/base.py
- pulse2percept/io/__init__.py
- pulse2percept/io/image.py
- pulse2percept/io/video.py
- pulse2percept/models/__init__.py
- pulse2percept/models/axon_map.py
- pulse2percept/models/base.py
- pulse2percept/models/scoreboard.py
- pulse2percept/models/watson2014.py
- pulse2percept/stimuli/__init__.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/base.py
- pulse2percept/utils/convolution.py
- pulse2percept/utils/deprecation.py
- pulse2percept/utils/parallel.py
- pulse2percept/utils/testing.py
- pulse2percept/viz/__init__.py
- pulse2percept/viz/axon_map.py
Documentation fixes & updates:
> [DOC] Installation & module description update

- azure-pipelines.yml
- pulse2percept/retina.py
- pulse2percept/tests/test_retina.py
- pulse2percept/utils.py
- pulse2percept/version.py
Bug fixes for v0.5:
- Fix "Cannot determine Numba type" error in `center_vector`
- `Horsager2009` does now respect `use_jit` option 
- `Nanduri2012` now allows switch between cython/fft
> [FIX] v0.5.1 

- doc/install.rst
- examples/models/plot_axon_map.py
- examples/models/plot_scoreboard.py
- examples/stimuli/plot_pulses.py
- pulse2percept/implants/alpha.py
- pulse2percept/implants/argus.py
- pulse2percept/implants/base.py
- pulse2percept/io/image.py
- pulse2percept/io/video.py
- pulse2percept/models/axon_map.py
- pulse2percept/models/base.py
- pulse2percept/models/scoreboard.py
- pulse2percept/models/watson2014.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/utils/base.py
- pulse2percept/utils/convolution.py
- pulse2percept/utils/deprecation.py
- pulse2percept/utils/parallel.py
- pulse2percept/utils/testing.py
- pulse2percept/viz/axon_map.py
> [DOC] Minor tweaks

- pulse2percept/implants/__init__.py
- pulse2percept/implants/base.py
Added code for a hexagonal grid of electrodes (alternative to ElectrodeGrid) to be used as a component for implants such as Prima.
> [ENH] Added ElectrodeGridHex class to implants.base

- README.rst
- examples/implants/plot_electrode_grid.py
- pulse2percept/implants/base.py
- pulse2percept/implants/tests/test_base.py
> [TST] [DOC] Tests and gallery example for the hexagonal grid

- .github/workflows/build.yml
- README.rst
- azure-pipelines.yml
- doc/install.rst
- pulse2percept/utils/convolution.py
- pulse2percept/utils/tests/test_convolution.py
- requirements-dev.txt
- setup.py
Support Python 3.8 by factoring out Numba.
> [ENH] [REF] Support Python 3.8

- pulse2percept/viz/axon_map.py
- pulse2percept/viz/tests/test_axon_map.py
Quick fixes for the plotting functions:
- Electrode size matches real electrode radius
- zorder for annotations & other elements
- elliptical optic nerve head
- New color scheme
> [FIX] plot_axon_map, plot_implant_on_axon_map

- pulse2percept/models/beyeler2019.py
Prune axon segments that don't significantly contribute to brightness (issue #211)
> [ENH] Speed up axon map model

- pulse2percept/implants/base.py
- pulse2percept/implants/electrodes.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/models/tests/test_beyeler2019.py
- pulse2percept/percepts/base.py
- pulse2percept/utils/geometry.py
- pulse2percept/utils/tests/test_geometry.py
- pulse2percept/viz/axon_map.py
> [ENH] Updated plot methods for grid, model, implant

- pulse2percept/percepts/base.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/stimuli/tests/test_images.py
- pulse2percept/stimuli/tests/test_pulse_trains.py
Encode images as pulse trains (issue #158), replaces old `image2pulsetrain`
> [ENH] Add ImageStimulus encoder

- doc/_static/css/custom.css
- doc/conf.py
- doc/requirements.txt
- doc/topics/datasets.rst
- doc/topics/implants.rst
- doc/topics/models.rst
- doc/topics/stimuli.rst
- examples/implants/plot_custom_electrode_array.py
- examples/implants/plot_electrode_grid.py
- examples/implants/plot_implants.py
- examples/models/plot_axon_map.py
- examples/models/plot_horsager2009.py
- examples/models/plot_scoreboard.py
- pulse2percept/__init__.py
- pulse2percept/implants/base.py
- pulse2percept/implants/electrode_arrays.py
- pulse2percept/models/base.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/models/tests/test_beyeler2019.py
- pulse2percept/percepts/base.py
- pulse2percept/percepts/tests/test_base.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/tests/test_base.py
- pulse2percept/utils/geometry.py
> [FIX] Plot methods, gallery, docs

- README.rst
- doc/conf.py
- examples/implants/plot_implants.py
- examples/stimuli/plot_image_stim.py
- pulse2percept/__init__.py
- pulse2percept/implants/electrodes.py
- pulse2percept/models/base.py
- pulse2percept/models/tests/test_base.py
- pulse2percept/models/tests/test_horsager2009.py
- pulse2percept/percepts/base.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/tests/test_images.py
- pulse2percept/utils/geometry.py
- requirements.txt
> [ENH] [DOC] Add ImageStimulus gallery example

- pulse2percept/percepts/base.py
- pulse2percept/percepts/tests/test_base.py
> [FIX] Playing and saving percepts

- examples/implants/plot_implants.py
- pulse2percept/implants/__init__.py
- pulse2percept/implants/argus.py
- pulse2percept/implants/bvt.py
- pulse2percept/implants/tests/test_bvt.py
Use the abbreviation of the device manufacturer (Bionic Vision Technologies)
> [REF] Rename BVA-24 to BVT-24

- CONTRIBUTING.rst
- doc/users/faq.rst
- doc/users/news.rst
- pulse2percept/datasets/base.py
- pulse2percept/datasets/beyeler2019.py
- pulse2percept/datasets/horsager2009.py
- pulse2percept/implants/base.py
- pulse2percept/implants/bvt.py
- pulse2percept/implants/electrodes.py
- pulse2percept/implants/prima.py
- pulse2percept/models/base.py
- pulse2percept/percepts/base.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/stimuli/pulses.py
- pulse2percept/stimuli/videos.py
- pulse2percept/utils/base.py
- pulse2percept/utils/geometry.py
- pulse2percept/utils/optimize.py
- pulse2percept/viz/argus.py
- pulse2percept/viz/base.py
Fix typos, add new references, fix rendering of `versionadded`
> [DOC] Various small fixes for the documentation

- CONTRIBUTING.rst
Update/streamline contribution guidelines
> [DOC] Update contribution guidelines

- pulse2percept/models/beyeler2019.py
Fixes the clipping in the axon map plotter (issue #243)
> [FIX] the clipping in the axon map plotter

- pulse2percept/stimuli/tests/test_videos.py
- pulse2percept/stimuli/videos.py
Add video processing methods. Same as image processing - applied to each frame of the video:
* `invert`: invert gray levels
* `rgb2gray`: convert RGB to grayscale
* `filter`: sobel, scharr, canny, median
* `apply`: apply a function to every frame
> [ENH] Add video processing methods

- pulse2percept/viz/base.py
[FIX] fix bug for missing function summary (see issue #259)
> [FIX] Update viz/base.py summary

- README.rst
fixed dead links in dependencies in `README.rst`
> [DOC] fixed dead links in dependencies (#268)

- pulse2percept/stimuli/images.py
> [ENH] rgb2gray when image is grayscale (#279)

- examples/models/plot_nanduri2012.py
Fix for the issue #267 for the Nanduri gallery example
> Update plot_nanduri2012.py for the issue #267

- pulse2percept/percepts/base.py
> [FIX] percept.play() truncated to 100 frames

- examples/stimuli/plot_image_stim.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/tests/test_images.py
Closes #269 by adding a `trim` method for `ImageStimulus`
> [ENH] Add ImageStimulus trim method

- pulse2percept/utils/__init__.py
- pulse2percept/utils/geometry.py
- pulse2percept/utils/tests/test_geometry.py
Addition of a util function delta_angle which returns signed difference between two angles.
Added relevant unit tests.
Closes issue #296
> [ENH] Added the util function delta_angle, along with related tests. Closes #296

- pulse2percept/percepts/base.py
> [ENH] Show time in percept.play()

- pulse2percept/stimuli/images.py
Corrects inconsistencies in the ImageStimulus Class' docstring raised in #252 . 
Closes #252 (added to link issue)
> [DOC] Update ImageStimulus docstring - Closes Issue #252

- pulse2percept/stimuli/videos.py
Brings the latest `percept.play()` updates to `VideoStimulus`: time in the title & `save_count` update
> [ENH] Update save_count, title of VideoStimulus

- .gitignore
- pulse2percept/percepts/base.py
- pulse2percept/stimuli/__init__.py
- pulse2percept/stimuli/psychophysics.py
- pulse2percept/stimuli/tests/test_psychophysics.py
- pulse2percept/stimuli/videos.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/array.py
- pulse2percept/utils/base.py
- pulse2percept/utils/tests/test_array.py
- pulse2percept/utils/tests/test_base.py
Add psychophysics stimuli: `GratingStimulus`, `BarStimulus`
> [ENH] Add GratingStimulus, BarStimulus

- examples/stimuli/plot_video_stim.py
> [DOC] Added a gallery example for using VideoStimulus

- doc/install.rst
Add NumPy ufunc error to the Troubleshooting guide (closes #142)
> [DOC] Address NumPy ufunc error in Troubleshooting guide

- CODE_OF_CONDUCT.md
- doc/topics/datasets.rst
- pulse2percept/datasets/__init__.py
- pulse2percept/datasets/tests/test_horsager2009.py
- pulse2percept/datasets/tests/test_nanduri2012.py
- pulse2percept/implants/electrode_arrays.py
- pulse2percept/model_selection/__init__.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/models/nanduri2012.py
- pulse2percept/models/tests/test_base.py
- pulse2percept/models/tests/test_nanduri2012.py
- pulse2percept/percepts/base.py
- pulse2percept/setup.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/stimuli/pulses.py
- pulse2percept/stimuli/tests/test_base.py
- pulse2percept/stimuli/tests/test_pulse_trains.py
- pulse2percept/stimuli/videos.py
- pulse2percept/utils/base.py
- pulse2percept/utils/tests/test_convolution.py
- pulse2percept/viz/__init__.py
Cleaning up code for the next release:
> [FIX] Pre-release cleanup

- pulse2percept/models/beyeler2019.py
This PR fixes the visualization of the axon map for left eyes (closes #364)
> [FIX] Axon map for left eyes

- doc/users/release_notes.rst
- pulse2percept/implants/electrode_arrays.py
- pulse2percept/implants/tests/test_base.py
Speed up the plotting of large electrode arrays by plotting a single `PatchCollection` (closes issue #374)
> [ENH] Speed up ElectrodeArray.plot()

- doc/topics/models.rst
- doc/users/release_notes.rst
- pulse2percept/models/__init__.py
- pulse2percept/models/_temporal.pyx
- pulse2percept/models/base.py
- pulse2percept/models/setup.py
- pulse2percept/models/temporal.py
- pulse2percept/models/tests/test_temporal.py
- pulse2percept/stimuli/base.py
Add a generic phosphene fading model, `FadingTemporal`. It assumes that phosphenes decay exponentially over time.
> [ENH] Add FadingTemporal model

- pulse2percept/implants/electrode_arrays.py
- pulse2percept/models/_beyeler2019.pyx
- pulse2percept/models/_horsager2009.pyx
- pulse2percept/models/_nanduri2012.pyx
- pulse2percept/setup.py
- pulse2percept/stimuli/_base.pyx
- pulse2percept/stimuli/base.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/_fast_math.pxd
- pulse2percept/utils/_fast_math.pyx
- pulse2percept/utils/base.py
- pulse2percept/utils/setup.py
- pulse2percept/utils/tests/test_base.py
This PR addresses various performance issues:
> [ENH] Various performance enhancements

- pulse2percept/implants/electrodes.py
- pulse2percept/percepts/base.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/images.py
- pulse2percept/stimuli/tests/test_base.py
- pulse2percept/stimuli/tests/test_images.py
- pulse2percept/stimuli/tests/test_videos.py
- pulse2percept/stimuli/videos.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/_array.pyx
- pulse2percept/utils/array.py
- pulse2percept/utils/images.py
- pulse2percept/utils/setup.py
- pulse2percept/utils/stats.py
- pulse2percept/utils/testing.py
- pulse2percept/utils/tests/test_array.py
- pulse2percept/utils/tests/test_images.py
This PR fixes miscellaneous usability issues & adds several upgrades for interacting with stimuli:
> [ENH] Various stimulus upgrades

- pulse2percept/datasets/beyeler2019.py
- pulse2percept/datasets/horsager2009.py
- pulse2percept/datasets/nanduri2012.py
- pulse2percept/implants/electrode_arrays.py
- pulse2percept/implants/electrodes.py
- pulse2percept/models/base.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/stimuli/__init__.py
- pulse2percept/stimuli/base.py
- pulse2percept/stimuli/pulse_trains.py
- pulse2percept/stimuli/pulses.py
- pulse2percept/stimuli/tests/test_base.py
- pulse2percept/stimuli/tests/test_pulse_trains.py
- pulse2percept/stimuli/tests/test_pulses.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/constants.py
- pulse2percept/utils/geometry.py
- pulse2percept/utils/images.py
- pulse2percept/utils/tests/test_constants.py
- pulse2percept/viz/__init__.py
- pulse2percept/viz/argus.py
- pulse2percept/viz/axon_map.py
- pulse2percept/viz/base.py
> [FIX] Order of display items in implant plots

- .github/workflows/diagram.yml
- README.rst
Add the [repo-visualizer](https://github.com/githubocto/repo-visualizer) diagram to the README
> [ENH] Add Octo visualizer

- .github/PULL_REQUEST_TEMPLATE.md
New PR template with updated checklist and clearer description
> [STY] Include checklist in PR template

- .github/workflows/wheels.yml
Pillow wheels are breaking again... Need to find a nonbroken version for Python 3.7/3.8
> [MAINT] Pillow wheels

- pulse2percept/utils/geometry.py
Provide a docstring for `cart2pol` and `pol2cart`. Especially the order of the return arguments was not clear
> [DOC] Add docstring for Cartesian <=> polar transform

- pulse2percept/models/beyeler2019.py
> [REF] Only pickle axon map parameters if they were regenerated

- examples/datasets/README.rst
- examples/datasets/plot_data_nanduri2012.py
- pulse2percept/datasets/nanduri2012.py
This PR adds an example of how to use the Nanduri 2012 dataset, using the ``pulse2percept.datasets.load_nanduri2012`` function.
Closes #254 
> [DOC] Add example of how to use the Nanduri 2012 dataset

- doc/users/news.rst
Closes #440 
Add Media coverage: https://www.pcmag.com/news/building-the-bionic-eyewith-car-tech
Add papers citing p2p before 2022
@mbeyeler
>  [DOC] Update paper citing

- pulse2percept/models/_beyeler2019.pyx
- pulse2percept/models/_granley2021.pyx
- pulse2percept/models/_horsager2009.pyx
- pulse2percept/models/_nanduri2012.pyx
- pulse2percept/models/_temporal.pyx
- pulse2percept/models/base.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/models/granley2021.py
- pulse2percept/models/horsager2009.py
- pulse2percept/models/nanduri2012.py
- pulse2percept/models/temporal.py
- pulse2percept/models/tests/test_base.py
This PR adds the ability to specify the number of threads to use during parallelization.
Closes #263
> [ENH] Let User Specify Number Of OpenMP Threads

- doc/topics/models.rst
- doc/users/references.rst
- examples/models/plot_thompson2003.py
- pulse2percept/models/__init__.py
- pulse2percept/models/_thompson2003.pyx
- pulse2percept/models/setup.py
- pulse2percept/models/tests/test_thompson2003.py
- pulse2percept/models/thompson2003.py
- pulse2percept/percepts/tests/test_base.py
- pulse2percept/utils/__init__.py
- pulse2percept/utils/array.py
- pulse2percept/utils/tests/test_array.py
Add `Thompson2003Model`, where all phosphenes are circular disks of a given size and gray level:
> [ENH] Add Thompson et al. (2003) model

- .codecov.yml
In this PR, I exclude test files from codecov. Exclusion pattern is based on the [codecov documentation](https://docs.codecov.com/docs/ignoring-paths).
Closes #467 
> [BUG] Exclude Test Files From Codecov

- doc/users/references.rst
- pulse2percept/implants/__init__.py
- pulse2percept/implants/bvt.py
- pulse2percept/implants/tests/test_bvt.py
Please include a summary of the change and which issue it closes below. Include relevant motivation and context.
Closes #464
Add BVT-44 to the implants
> [ENH] Add BVT-44

- README.rst
- pulse2percept/models/base.py
- pulse2percept/stimuli/base.py
- pulse2percept/utils/parallel.py
- requirements-dev.txt
- requirements.txt
- setup.py
JobLib doesn't need to be a required dependency anymore.
> [MNT] Make Joblib optional

- doc/users/references.rst
- examples/datasets/plot_greenwald2009.py
- examples/models/plot_granley2021_biphasic.py
- examples/stimuli/plot_psychophysics.py
Adds a tutorial-style example for the BiphasicAxonMapModel
> [DOC] BiphasicAxonMapModel example

- README.rst
- doc/install.rst
Update/simplify installation instructions. You really only need to install from source if you want to contribute to p2p
> [DOC] Update/simplify installation instructions

- requirements.txt
Please include a summary of the change and which issue it closes below. Include relevant motivation and context.
Closes #(issue)
> [FIX] Remove ambiguity in double scipy version requirement.

- doc/topics/implants.rst
- doc/users/references.rst
- examples/implants/plot_implants.py
- pulse2percept/implants/__init__.py
- pulse2percept/implants/imie.py
- pulse2percept/implants/tests/test_imie.py
> [ENH] Add IMIE implant

- doc/topics/datasets.rst
- doc/users/references.rst
- pulse2percept/datasets/__init__.py
- pulse2percept/datasets/base.py
- pulse2percept/datasets/han2021.py
- pulse2percept/datasets/tests/test_han2021.py
- pulse2percept/stimuli/videos.py
Add fetch method for Han et al. (2021) dataset 
Closes #371
> [ENH] Add fetch method for Han et al. (2021) dataset 

- pulse2percept/implants/cortex/cortivis.py
- pulse2percept/models/cortex/tests/test_base.py
> [ENH] Update to match 2023 Cortivis electrode numbering

- pulse2percept/implants/cortex/cortivis.py
- pulse2percept/implants/cortex/tests/test_cortivis.py
- pulse2percept/models/cortex/tests/test_base.py
- pulse2percept/topography/cortex.py
- pulse2percept/topography/tests/test_cortex.py
Changes default values of Polimeni mapping to be closer to human fit
> [REF] Default values for Polimeni mapping

- pulse2percept/models/granley2021.py
Updates docstrings in `Granley2021.py` to reflect changes since the original paper. Closes #575
> [DOC] Update Biphasic docstrings

- pulse2percept/__init__.py
- pulse2percept/implants/__init__.py
- pulse2percept/models/__init__.py
- pulse2percept/models/beyeler2019.py
- pulse2percept/models/setup.py
- pulse2percept/models/thompson2003.py
- pulse2percept/setup.py
Update pulse2percept's setup.py & __init__.py to include new topography and implants.cortex subpackages.
Update pulse2percept/models setup.py & __init__.py to include models.cortex subpackage.
Update pulse2percept/implants __init__.py to include implants.cortex subpackage.
Cortex models are importable now after using `pip install git+[...]`. 
Closes #562
> [MNT] Update package setup for cortex packages

- .readthedocs.yml
Fix doc folder for read the docs
> [DOC][FIX] Docs folder

- doc/conf.py
- doc/index.rst
- doc/topics/implants.rst
- examples/models/plot_retinotopy.py
- pulse2percept/__init__.py
- pulse2percept/implants/__init__.py
- pulse2percept/implants/cortex/__init__.py
- pulse2percept/implants/cortex/cortivis.py
- pulse2percept/implants/cortex/icvp.py
- pulse2percept/implants/cortex/orion.py
- pulse2percept/models/__init__.py
- pulse2percept/models/base.py
- pulse2percept/models/cortex/__init__.py
- pulse2percept/models/cortex/base.py
- pulse2percept/topography/__init__.py
- pulse2percept/topography/cortex.py
- pulse2percept/topography/retina.py
Summary of changes:
- fix & merge Luke's cortex examples and API docstrings
- fix sphinx submenu layout
- remove minigallery in implants concept as it doesn't render correctly
> [DOC] Fix sphinx issues and merge Luke's examples

- pulse2percept/models/cortex/dynaphos.py
At amplitude 0, the phosphenes generated by Dynaphos have size 0. With this change, we only update the phosphene size if amplitude > 0, on an electrode-by-electrode basis.
We also allow t_percept to extend longer than the stimulus time by filling in the extra time with an assumed amplitude of 0.
Old percept brightness over time:
New percept brightness over time:
> [FIX] Fix Dynaphos model phosphene size at amplitude 0

- doc/topics/models.rst
- examples/models/plot_dynaphos.py
- pulse2percept/models/cortex/dynaphos.py
Adds an example for Dynaphos to the model example gallery. This PR also slightly modifies the Dynaphos docstring due to a formatting issue. 
Part of #532
> [DOC] Add Dynaphos to example gallery

- doc/topics/cortical.rst
- doc/users/references.rst
- examples/implants/plot_implants_cortical.py
- examples/models/plot_neuropythy.py
- examples/models/plot_visual_field_maps.py
Adds example with neuropythy and neuralink
> [DOC] Neuropythy example

- pulse2percept/models/cortex/dynaphos.py
Add docstrings for dynaphos model
> [DOC] Add docstrings

- .github/workflows/wheels.yml
Update wheels for torch branch and to fix windows bug
> [ENH] Update wheels

- .github/workflows/build.yml
- .github/workflows/wheels.yml
- pulse2percept/percepts/tests/test_base.py
- pulse2percept/stimuli/tests/test_videos.py
> Merge changes from master

- pulse2percept/models/cortex/base.py
- pulse2percept/topography/tests/test_neuropythy.py
Support for 3D Scoreboard Torch Models
> [ENH] 3D Scoreboard Torch

- setup.py
Warns users if they attempt to install p2p on an unsupported platform
> [MNT] Warn when attempting install on unsupported platforms

- README.rst
- doc/users/references.rst
- doc/users/release_notes.rst
- examples/models/plot_dynaphos.py
- pulse2percept/datasets/__init__.py
- pulse2percept/implants/base.py
- pulse2percept/implants/cortex/cortivis.py
- pulse2percept/implants/cortex/icvp.py
- pulse2percept/implants/cortex/neuralink.py
- pulse2percept/implants/imie.py
- pulse2percept/models/cortex/dynaphos.py
- pyproject.toml
> Release 0.9.0
